- name: "Install runtime"
  hosts: [ "web" ]
  tasks:
    - name: "apt get install"
      apt:
        name: "{{item}}"
      with_items: "{{runtime.software}}"


- name: "Configure runtime"
  hosts: [ "web" ]
  tags: [ 'config', 'php' ]
  tasks:

  - name: "php - php.ini changes"
    lineinfile:
      dest: "{{item[1]}}"
      regexp: "{{item[0].pattern}}"
      line: "{{item[0].line}}"
      state: present
    with_nested:
      - "{{runtime.php.configuration}}"
      - "{{runtime.php.files}}"
    notify:
      - "restart php-fpm"

  handlers:
    - name: "restart php-fpm"
      service:
        name: "php5-fpm"
        state: restarted


- name: "Configure nginx"
  hosts: [ "web" ]
  tags: [ 'config', 'nginx' ]
  tasks:

  - name: "nginx - remove default configuration"
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: "nginx - create/update configuration"          
    template:
      src: "templates/nginx_app.conf"
      dest: "/etc/nginx/sites-available/{{app.name}}"
    notify: 
      - "restart nginx"

  - name: "nginx - enable configuration"
    file:
      src: "/etc/nginx/sites-available/{{app.name}}"
      dest: "/etc/nginx/sites-enabled/{{app.name}}"
      state: link
    notify: 
      - "restart nginx"

  handlers:
    - name: "restart nginx"
      service:
        name: "nginx"
        state: "restarted"

